# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f52d8c9960ca52283c92a92d9100d3d57d47bf1d09de02e3058a9634ae3ec72a74146a4e942479b7fde42a9b2d805f95fc1e37e3101e64b8e868bc45f1f9d096

test:
  secret_key_base: 56898afc7f1cc808951ec22f385fe9bb0e146cd26aeb07d2f7b55f42c9fbe12aa646a1892ba0d86dd3acbb926308e58fae996ea00563bd534fdedb2c91ed4a3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
